### ISSUE TITLE
Wealth List and Wealth Overlay Disagree

### ISSUE THREAD

**Issue by TheKevJames** [legodude17/VanillaUIExpanded#16]
The Wealth List only seems to include claimed, non-flooring items on the map, whereas the wealth overlay includes everything. I'm not actually sure which is "correct" -- my understanding of rimworld wealth would point to the overlay being correct, but I'm not an expert! -- but I would expect to see the same details in both places.

Repro:
* check wealth list, verify it doesn't contain a ruined table/column/sarcophagus/etc
* claim the relevant ruin
* check wealth list again, now the claimed item shows up

**Comment by legodude17** [comment]
This is intentional. The wealth list displays what contributes to colony wealth, whilst the wealth overlay is meant to show how much things are worth, regardless of if they are contributing to colony wealth or not.

**Comment by TheKevJames** [comment]
@legodude17 ah, thanks for clarifying! I hadn't realized they changed the logic to make flooring wealth not count.
