### ISSUE TITLE
After installing the mod at the last position, I have no power

### ISSUE THREAD

**Issue by sharky98** [legodude17/VanillaUIExpanded#2]
Hello,

For some reason, all my power building a treated as not generating power anymore when installing this mod. Here is my [modlist](https://gist.github.com/sharky98/32a98477a58101922c586459ba1266de).

I've tried to put that mod both way at the top or way at the bottom, same result. I've tried deconstruct and building a new geothermal, but when it finished to build, it just vanished! In fact, it does that with all items tested (table, chair, etc.)

I do see a lot of red log in the debug, that were not there before installing the mod. So much in fact, that I am not able to get the log from the building failure as I get to the max message in a few seconds.
```
Exception ticking GeothermalGenerator1054103 (at (214, 0, 129)): System.NullReferenceException: Object reference not set to an instance of an object
  at RimWorld.CompPowerPlantSteam.CompTick () [0x0005c] in <cdbd0ed5089a418da09b9a259f9dbd8f>:0 
  at Verse.ThingWithComps.Tick () [0x00024] in <cdbd0ed5089a418da09b9a259f9dbd8f>:0 
  at Verse.TickList.Tick () [0x0015c] in <cdbd0ed5089a418da09b9a259f9dbd8f>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.TickList:Tick ()
Verse.TickManager:DoSingleTick ()
Verse.TickManager:TickManagerUpdate ()
Verse.Game:UpdatePlay ()
Verse.Root_Play:Update ()
```

No power
![image](https://user-images.githubusercontent.com/8150191/153649481-c4b7b0c7-bde4-41a9-b5f7-e9a874c8759d.png)

Build fail
![image](https://user-images.githubusercontent.com/8150191/153649883-047dd34b-df5a-4ca5-b8f5-eaba1808fe38.png)
![image](https://user-images.githubusercontent.com/8150191/153649933-c147ef93-94a4-40a9-a700-f1a75cb00d03.png)
![image](https://user-images.githubusercontent.com/8150191/153649959-d43e1987-9457-4303-93c2-d08e6ae97f2b.png)

**Comment by legodude17** [comment]
That error does not look related to Vanilla UI Expanded.

**Comment by sharky98** [comment]
Yet it's only after installing that mod that this occurs. I do not have the DLC. I've also tried to remove Hospitality. Here the full [hugslib log](https://gist.github.com/29e5945f93bbfba5b8aabdef930a126d).

**Comment by sharky98** [comment]
Looks like I am not alone, from the Steam comment of Igopt.
```
Hello, this mod seems to make all my power conduits and power producing buildings unable to connect to anything (the power conduits wont even connect to each other) it also stops the buildings from producing power. I have tried moving it to the bottom of the load order but the problem persists.

Here is the Hugslib output log:
https://gist.github.com/HugsLibRecordKeeper/b8f5ee81d365990ff56ce15b27156520
```

**Comment by legodude17** [comment]
Should be fixed in latest version.

**Comment by sharky98** [comment]
It is indeed fixed. Thank you very much! 👍
