### ISSUE TITLE
Incompatiblity with RimSaves

### ISSUE THREAD

**Issue by Honza2268** [legodude17/VanillaUIExpanded#3]
Hello,
I have found this issue:

When exporting architect configuration, RimSaves window opens without the ability to save. Tested both load orders.

![image](https://user-images.githubusercontent.com/36334510/153715493-52bd4392-e2df-45c6-bd12-8c2c4c929b86.png)

Opening the import window with previously created configurations throws RimSaves errors (unexpected path, missing expected files)

![image](https://user-images.githubusercontent.com/36334510/153715626-fb46dcf5-ffcb-4a86-b07a-f2d3505ddef5.png)

**Comment by mthiel** [comment]
Testing a fix for this now.

**Comment by mthiel** [comment]
PR submitted

**Comment by mthiel** [comment]
@Honza2268 the latest release contains a fix for this issue. Are you still experiencing this problem?

**Comment by Honza2268** [comment]
fix is confirmed working solo and in 700+ modpack

**Comment by legodude17** [comment]
Awesome!
